version: '3.5'

services:
  sandcastle-db:
    image: mongo


  sandcastle-backend:
    image: ${DOCKER_REGISTRY-}sandcastlebackend
    build:
      context: ../Backend/SandCastle-BackEnd
      dockerfile: ./SandCastle-BackEnd/Dockerfile
  sandcastle-frontend:
    image: ${DOCKER_REGISTRY-}sandcastlefrontend
    build:
      context: ../Frontend/sandcastle-frontend
      dockerfile: ./Dockerfile
volumes:
    mongo_data: