version: '3.4'

services:
  sandcastle-db:
    image: mongo


  sandcastle-backend:
    image: ${DOCKER_REGISTRY-}sandcastlebackend
    build:
      context: .
      dockerfile: SandCastle-BackEnd/Dockerfile

volumes:
    mongo_data: